print("Numele,Prenumele:Moscvin Andreea")
print("Data,Luna,Anul Nașterii: 26.08.2004")
print("Locul Nașterii: mun.Chișinău, Republica Moldova")
print("Domiciliul: str.Strii 1/37")
print("Numărul de telefon: 069533906")
print("Școala: Instituția Publică Liceul Teoretic Mihai Eminescu, clasa a 10-a C")
print("Studii: 2019-2020 gimnaziul IPLT Mihai Eminescu, 2011-2018 LT Lucian Blaga")
print("Abilități: cunosc limba engleză și franceza")
print("Operare la calculator în aplicațiile: Microsoft Word, Microsoft Excel, Mirosoft Power Point, PASCAL, PYTHON")
print("Hobby: mă ocup cu limbile străine, muzica și sportul")
print("Recomandări, referințe: Lupașcu Natalia")
print("Semnătura: MAndreea")
print("Data: 15.09.2020")